### ISSUE TITLE
Update documentation to reflect how to enable easy access to control terminal

### ISSUE THREAD

**Issue by cristiroma** [eea/eea.docker.varnish#20]
Please update the documentation to reflect how to configure the Varnish control terminal running usually on port 6082:

Here's the snippet I am using:

```
    volumes:
      - ./varnish.secret:/etc/varnish/secret
    environment:
      PARAM_VALUE: "-S /etc/varnish/secret"
      ADMIN_PORT: ":6082"
```

Sample content of `secret` file:

```
a40ff8c617404b78d74-2a6707d565ef
```
